### ISSUE TITLE
Sistema de Login e Session

### ISSUE THREAD

**Issue by 1giodev** [1giodev/KanBan2020#2]
**Sistema de Login**

Criar o Sistema de Login, Registro e Manutenção de Usuários

- [x] Cadastro de Usuário
- [x] Confirmação de E-mail
- [x] Recuperação de Acesso
- [x] Atualização de Dados do Usuário
- [x] Login/Logout

**Comment by eugiioo-dev** [comment]
Implementado a View de Login e a Controller.
