### ISSUE TITLE
Configurar Envio de E-mail pelo MailGun

### ISSUE THREAD

**Issue by 1giodev** [1giodev/KanBan2020#3]
**Configurar Envio de E-mail pelo MailGun**

- [x] Configurar o Envio de E-mail pelo MailGun, usar exemplo do projeto EnviarEmail.
- [x] Criar Template de E-mail que será usado para notificar o usuário em diversos momentos como por exemplo na criação de quadros, alteração de senha, confirmação de e-mail.

**Comment by eugiioo-dev** [comment]
Envio de E-mail Configurado!

**Comment by 1giodev** [comment]
Canceled
